services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    image: f3rym/instance-services-backend
    container_name: backend
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/v1/datacenters || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
  frontend:
    image: f3rym/instance-services-frontend:395b07a65cf05af30dd88ef15554d15985f1d4b3
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      backend:
        condition: service_healthy
volumes:
  pgdata:
    external: true
