apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-pgdata-pvc"
spec:
  storageClassName: {{ .Values.db.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.db.storage }}"
