apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.db.service.name }}"
spec:
  selector:
    app: "{{ .Release.Name }}-postgres"
  ports:
    - targetPort: {{ .Values.db.port }}
      port: {{ .Values.db.service.port }}