apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-backend"
  labels:
    app: "{{ .Release.Name }}-backend"
spec:
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-backend"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-backend"
    spec:
      containers:
        - image: "{{ .Values.backend.image}}:{{ .Values.backend.tag }}"
          name: "{{ .Release.Name }}-backend-container"
          livenessProbe:
            httpGet:
              path: "{{ .Values.backend.livenessProbe.httpGet.path }}"
              port: {{ .Values.backend.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: "{{ .Values.backend.readinessProbe.httpGet.path }}"
              port: {{ .Values.backend.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.backend.readinessProbe.failureThreshold }}
          startupProbe:
            httpGet:
              path: "{{ .Values.backend.startupProbe.httpGet.path }}"
              port: {{ .Values.backend.startupProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.backend.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.backend.startupProbe.failureThreshold }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: DB_SERVICE
              value: "{{ .Release.Name }}-{{ .Values.db.service.name }}"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.credentials.secretName }}
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.credentials.secretName }}
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.credentials.secretName }}
                  key: password
          resources:
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu }}
              memory: {{ .Values.backend.resources.limits.memory }}
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu }}
              memory: {{ .Values.backend.resources.requests.memory }}