apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.backend.service.name }}"
spec:
  selector:
    app: "{{ .Release.Name }}-backend"
  ports:
    - targetPort: {{ .Values.backend.service.port }}
      port: {{ .Values.backend.service.port }}